"""
generate-ide-config.py — generates .cursorrules, CLAUDE.md, and Antigravity
skill files from templates/agent-rules.yaml, the single source of truth
(SPECS.md §4, §13, §22 Phase 5).

Called by the post-checkout hook instead of embedding IDE-rule content
inline — editing templates/agent-rules.yaml is now the only way to change
what gets written to .cursorrules / CLAUDE.md / .agents/skills/*/skill.md.

Idempotent: never overwrites an existing .cursorrules, CLAUDE.md, or
skill.md (same behavior as the hook's previous `[ ! -f ... ]` guards).

Usage:
    python3 generate-ide-config.py \\
        --repo-root /path/to/repo \\
        --rules-file /path/to/templates/agent-rules.yaml \\
        --stack ts-react|python-fastapi|go|generic \\
        --project-name myproject --owner-id me@example.com \\
        --otel-endpoint http://localhost:6006 --test-cmd "pytest" \\
        --framework-version 1.0.0
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path


def _load_rules(rules_file: Path) -> dict:
    try:
        import yaml  # type: ignore
    except ImportError:
        print(
            "❌ generate-ide-config.py requires pyyaml (pip install -r requirements.txt). "
            "IDE config was NOT regenerated.",
            file=sys.stderr,
        )
        sys.exit(1)
    with rules_file.open() as fh:
        return yaml.safe_load(fh) or {}


def _playbook_skills(rules: dict) -> list[dict]:
    """Skills shaped as a doc pointer (`design_review`, `validation_review`)
    rather than a pillar compression — distinguished by carrying `doc`, which
    a pillars-shaped skill never does. Kept as one function so every renderer
    that needs this list gets it the same way (`parameterize-dont-clone`)."""
    return [s for s in rules.get("skills", []) if s.get("doc")]


def _playbook_location(doc: str) -> str:
    """Where a generated file should tell the reader to find `doc`.

    `doc` is a path under the FRAMEWORK's own docs/ — not vendored into a
    tenant repo or written by the post-checkout hook the way .cursorrules /
    CLAUDE.md / etc. are. Only scripts/, templates/, and (as of this pair)
    these two named files reach ~/.agent-framework — see install-ai-stack.sh.
    So there is no single resolvable path; there are two, and the reader
    picks whichever matches how AgentSmith got onto this machine.
    """
    filename = doc.rsplit("/", 1)[-1]
    return (
        f"`$AGENTSMITH_DIR/{doc}` if you're on a live framework checkout, "
        f"or `~/.agent-framework/docs/{filename}` if AgentSmith was installed "
        f"from the package"
    )


def _render_cursorrules(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    lines = [
        "# AgentSmith — Agent Guardrails",
        f"# Project: {ctx['project_name']} | Owner: {ctx['owner_id']}",
        f"# Auto-generated by AgentSmith v{ctx['framework_version']} "
        f"from templates/agent-rules.yaml — do not edit this file directly.",
        "",
    ]

    pillar_titles = {
        1: "REQUIREMENTS & DESIGN",
        2: "BUILD ARCHITECTURE (Ponytail Rules)",
        3: "TRACING & EVALUATIONS",
        4: "TESTING GUARDRAILS",
        5: "OPERATIONS & SELF-IMPROVEMENT",
        6: "INTERFACE CONSTRAINTS (Caveman Compression)",
        7: "STACK-SPECIFIC RULES",
        8: "OBSERVABILITY WIRE",
        9: "MULTI-AGENT ORCHESTRATION",
        10: "COST-OPTIMISATION ROUTING",
    }

    for pillar in rules.get("pillars", []):
        pid = pillar["id"]
        title = pillar_titles.get(pid, pillar["name"].upper())
        rule_text = pillar["rule"].strip()
        # Substitute the same placeholders the old inline heredocs used.
        rule_text = (
            rule_text.replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
            .replace("{{OWNER_ID}}", ctx["owner_id"])
            .replace("{{PROJECT_NAME}}", ctx["project_name"])
        )
        lines.append(f"## {pid}. {title}")
        lines.append(f"- {rule_text}")
        if pid == 3:
            lines.append(
                f"- OTel endpoint for this project: {ctx['otel_endpoint']}/v1/traces"
            )
        if pid == 4:
            lines.append(f"- Test command for this project: {ctx['test_cmd']}")
        lines.append("")

    stack_def = (rules.get("stacks") or {}).get(stack)
    next_no = len(rules.get("pillars", [])) + 1
    if stack_def:
        # Numbered after the last pillar, not hardcoded. This said "11" from
        # when there were ten pillars; adding four gave the file two sections
        # numbered 11 — the addendum and Untrusted Content — which is exactly
        # the kind of quiet inconsistency an agent reading the rules trips on.
        lines.append(f"## {next_no}. {stack.upper()} ADDENDUM")
        for r in stack_def.get("additional_rules", []):
            lines.append(f"- {r}")
        lines.append("")
        next_no += 1

    playbooks = _playbook_skills(rules)
    if playbooks:
        lines.append(f"## {next_no}. DESIGN & VALIDATION PLAYBOOKS")
        for pb in playbooks:
            lines.append(
                f"- **{pb['title']}** ({pb['trigger']}) — {_playbook_location(pb['doc'])}."
            )
        lines.append("")

    return "\n".join(lines)


def _render_claude_md(rules: dict, ctx: dict[str, str]) -> str:
    playbooks = _playbook_skills(rules)
    playbook_section = ""
    if playbooks:
        pb_lines = "\n".join(
            f"- **{pb['title']}** ({pb['trigger']}) — {_playbook_location(pb['doc'])}."
            for pb in playbooks
        )
        playbook_section = f"""
## Design & Validation Playbooks
{pb_lines}
"""
    return f"""# AgentSmith — Claude Code Instructions
# Project: {ctx["project_name"]} | Owner: {ctx["owner_id"]}
# Auto-generated from templates/agent-rules.yaml — do not edit this file directly.

## Compliance
Follow all rules in `.cursorrules` exactly. They are not suggestions.

## Session Start Checklist
1. Read `.agent-history.log` — surface any unresolved MAJOR/CRITICAL entries to the user.
2. Check `.agent-rfc/` — confirm a spec exists before touching any source file.
3. Query the Knowledge Graph: `python3 scripts/local_knowledge_graph.py` to identify dependencies.

## Test Command
```
{ctx["test_cmd"]}
```

## Observability
- OTel endpoint: {ctx["otel_endpoint"]}/v1/traces
- Emit spans for every tool call, LLM invocation, and file write.
{playbook_section}
## Output Format
Terse by default — code, commands, data. Skip preambles and filler summaries.
Being terse is not being silent: state plainly what failed and why you think so,
any risk you are taking, and any assumption you had to make. The session-start
escalation above is worthless if it arrives as a code block nobody can read.
"""


def _render_agents_md(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    """AGENTS.md — the convention Codex reads, and increasingly the cross-tool one.

    Deliberately self-contained rather than a pointer to `.cursorrules`. CLAUDE.md
    can say "follow .cursorrules" because Claude Code reliably opens neighbouring
    files on request; an agent that only ingests AGENTS.md at session start would
    get a rule file consisting of one redirect it may never follow. The cost is
    some duplication between two generated files, which is acceptable because both
    are generated — they cannot drift from each other, only from the YAML, and
    --check-only catches that.
    """
    pillars = "\n".join(
        f"{p['id']}. **{p['name']}** — {' '.join(str(p['rule']).split())}"
        for p in rules.get("pillars", [])
    )
    stack_def = (rules.get("stacks") or {}).get(stack) or {}
    addendum = "\n".join(f"- {r}" for r in stack_def.get("additional_rules", [])) or "- (none for this stack)"
    playbooks = _playbook_skills(rules)
    playbook_section = ""
    if playbooks:
        pb_lines = "\n".join(
            f"- **{pb['title']}** ({pb['trigger']}) — {_playbook_location(pb['doc'])}."
            for pb in playbooks
        )
        playbook_section = f"""
## Design & Validation Playbooks
{pb_lines}
"""
    return f"""# AGENTS.md — {ctx["project_name"]}
<!-- Owner: {ctx["owner_id"]} -->
<!-- Auto-generated from templates/agent-rules.yaml — do not edit this file directly. -->

These are the operating rules for any coding agent working in this repository.
They are not style preferences; each one exists because its absence caused a
real failure. Where a rule explains itself, that reasoning is the point — follow
the intent, not just the letter.

## Session start
1. Read `.agent-history.log` and surface unresolved MAJOR/CRITICAL entries.
2. Confirm a spec exists in `.agent-rfc/` before editing any source file.
3. Query the Knowledge Graph (`python3 scripts/local_knowledge_graph.py`) for dependencies.

## Rules
{pillars}

## Stack ({stack})
{addendum}
{playbook_section}
## Test command
```
{ctx["test_cmd"]}
```

## Observability
Emit OTel spans for every tool call, LLM invocation and file write to
{ctx["otel_endpoint"]}/v1/traces.
"""


def _render_copilot_instructions(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    """`.github/copilot-instructions.md` — repo-wide instructions for GitHub Copilot.

    Deliberately the SHORT one. Copilot prepends this to requests rather than
    reading it once at session start, so length is a recurring cost paid on every
    completion, and a fourteen-pillar essay would crowd out the code the model is
    supposed to be looking at. The pillars are compressed to their imperative —
    the reasoning that makes AGENTS.md worth reading is exactly what does not
    survive that budget.

    That trade means Copilot gets the rules but not the arguments, so this file
    points at AGENTS.md for anything a reader needs to weigh rather than obey.
    """
    lines = []
    for p in rules.get("pillars", []):
        # First sentence only: it carries the instruction, the rest carries the why.
        first = " ".join(str(p["rule"]).split()).split(". ")[0].rstrip(".")
        lines.append(f"- **{p['name']}**: {first}.")
    stack_def = (rules.get("stacks") or {}).get(stack) or {}
    stack_rules = "\n".join(f"- {r}" for r in stack_def.get("additional_rules", []))
    # One line, not a bullet per playbook — the budget argument above applies
    # here exactly as it does to the pillars: name that they exist and where,
    # leave the "why" and the trigger detail to AGENTS.md.
    playbook_names = ", ".join(pb["title"].split(" — ")[0] for pb in _playbook_skills(rules))
    playbook_line = (
        f"\nDesign/validation playbooks ({playbook_names}): see `AGENTS.md`.\n"
        if playbook_names
        else ""
    )
    return f"""<!-- Auto-generated from templates/agent-rules.yaml — do not edit directly. -->
# Copilot instructions — {ctx["project_name"]}

Follow these when suggesting or editing code in this repository. Full reasoning
for each rule is in `AGENTS.md`; this file is the condensed form Copilot sees on
every request.

{chr(10).join(lines)}

## {stack} specifics
{stack_rules or "- (none for this stack)"}
{playbook_line}
Tests: `{ctx["test_cmd"]}`
"""


def _render_gemini_md(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    """GEMINI.md — read by Gemini CLI at session start, like CLAUDE.md.

    Full-length, same as AGENTS.md: this is loaded once per session rather than
    per request, so the reasoning earns its tokens. Kept as its own renderer
    rather than aliasing AGENTS.md because the session-start contract differs —
    Gemini CLI resolves its tool names through this file, so the header says so
    explicitly rather than leaving a Claude-shaped instruction to be guessed at.
    """
    body = _render_agents_md(rules, stack, ctx)
    body = body.replace(
        f'# AGENTS.md — {ctx["project_name"]}',
        f'# GEMINI.md — {ctx["project_name"]}',
        1,
    )
    return body.replace(
        "These are the operating rules for any coding agent working in this repository.",
        "These are the operating rules for any coding agent working in this repository.\n"
        "Gemini CLI: tool names in these rules follow the Claude Code convention —\n"
        "map them to your equivalents rather than skipping the rule.",
        1,
    )


def _render_skill(skill: dict, rules: dict, ctx: dict[str, str]) -> str:
    lines = [
        f"# {skill['title']}",
        "## Trigger",
        skill["trigger"],
        "",
        "## Instructions",
    ]

    if skill.get("doc"):
        # Doc-pointer skill: the content lives in the referenced file, not
        # compressed from pillars — see the comment beside these two entries
        # in templates/agent-rules.yaml for why it isn't inlined here.
        summary = " ".join(str(skill.get("summary", "")).split())
        lines.append(f"- Before proceeding, read {_playbook_location(skill['doc'])}.")
        if summary:
            lines.append(f"- {summary}")
        lines.append(f"- Owner: {ctx['owner_id']} | Project: {ctx['project_name']}")
        return "\n".join(lines) + "\n"

    pillar_by_id = {p["id"]: p for p in rules.get("pillars", [])}
    for pid in skill.get("pillars", []):
        pillar = pillar_by_id.get(pid)
        if not pillar:
            continue
        rule_text = (
            pillar["rule"]
            .strip()
            .replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
        )
        lines.append(f"- ({pillar['name']}) {rule_text}")
    lines.append(f"- OTel endpoint: {ctx['otel_endpoint']}/v1/traces")
    lines.append(f"- Owner: {ctx['owner_id']} | Project: {ctx['project_name']}")
    return "\n".join(lines) + "\n"


def _detect_stack(repo_root: Path) -> tuple[str, str]:
    """Mirror hooks/post-checkout's bash stack detection. Returns (stack, default_test_cmd)."""
    if (repo_root / "package.json").exists():
        return "ts-react", "CI=true npm test"
    if (
        (repo_root / "requirements.txt").exists()
        or (repo_root / "pyproject.toml").exists()
        or (repo_root / "Pipfile").exists()
    ):
        return "python-fastapi", "pytest"
    if (repo_root / "go.mod").exists():
        return "go", "go test -race ./..."
    return "generic", "echo 'No test command configured'"


def _default_project_name(repo_root: Path) -> str:
    try:
        url = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        ).stdout.strip()
        if url:
            return url.rsplit("/", 1)[-1].removesuffix(".git")
    # fail-open: no git remote / not a git repo / git not installed all fall back to the
    # dir name below
    except Exception:
        pass
    return repo_root.resolve().name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--rules-file", default=None)
    ap.add_argument("--stack", default=None)
    ap.add_argument("--project-name", default=None)
    ap.add_argument("--owner-id", default=None)
    ap.add_argument("--otel-endpoint", default=None)
    ap.add_argument("--test-cmd", default=None)
    ap.add_argument("--framework-version", default=None)
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="Don't write files — regenerate in memory and diff against what's "
        "already committed. Exits 1 if .cursorrules/CLAUDE.md/skill.md have "
        "drifted from templates/agent-rules.yaml (Pillar 6/7 CI gate).",
    )
    args = ap.parse_args()

    repo_root = Path(args.repo_root)
    detected_stack, detected_test_cmd = _detect_stack(repo_root)

    rules_file = (
        Path(args.rules_file)
        if args.rules_file
        else repo_root / "templates" / "agent-rules.yaml"
    )
    if not rules_file.exists():
        if args.check_only:
            print(f"ℹ️  No rules file at {rules_file} — IDE config drift check skipped.")
            sys.exit(0)
        print(
            f"❌ Rules file not found: {rules_file}. IDE config was NOT regenerated.",
            file=sys.stderr,
        )
        sys.exit(1)

    stack = args.stack or detected_stack
    rules = _load_rules(rules_file)
    ctx = {
        "project_name": args.project_name or _default_project_name(repo_root),
        "owner_id": args.owner_id
        or os.environ.get("AGENT_OWNER_ID", "unknown@unknown"),
        "otel_endpoint": args.otel_endpoint
        or os.environ.get("AGENT_PHOENIX_ENDPOINT", "http://localhost:6006"),
        "test_cmd": args.test_cmd or detected_test_cmd,
        "framework_version": args.framework_version
        or os.environ.get("FRAMEWORK_VERSION", "1.0.0"),
    }

    if args.check_only:
        sys.exit(0 if _check_drift(repo_root, rules, stack, ctx) else 1)

    cursorrules_path = repo_root / ".cursorrules"
    if not cursorrules_path.exists():
        cursorrules_path.write_text(_render_cursorrules(rules, stack, ctx))
        print(
            f"✅ Written .cursorrules ({len(rules.get('pillars', []))} pillars "
            f"+ {stack} addendum) from agent-rules.yaml"
        )

    claude_md_path = repo_root / "CLAUDE.md"
    if not claude_md_path.exists():
        claude_md_path.write_text(_render_claude_md(rules, ctx))
        print("✅ Written CLAUDE.md from agent-rules.yaml")

    agents_md_path = repo_root / "AGENTS.md"
    if not agents_md_path.exists():
        agents_md_path.write_text(_render_agents_md(rules, stack, ctx))
        print("✅ Written AGENTS.md (Codex / cross-tool) from agent-rules.yaml")

    gemini_md_path = repo_root / "GEMINI.md"
    if not gemini_md_path.exists():
        gemini_md_path.write_text(_render_gemini_md(rules, stack, ctx))
        print("✅ Written GEMINI.md (Gemini CLI) from agent-rules.yaml")

    copilot_path = repo_root / ".github" / "copilot-instructions.md"
    if not copilot_path.exists():
        copilot_path.parent.mkdir(parents=True, exist_ok=True)
        copilot_path.write_text(_render_copilot_instructions(rules, stack, ctx))
        print("✅ Written .github/copilot-instructions.md from agent-rules.yaml")

    # Pillar 5 tells every agent to read this on session start. A fresh repo had
    # none, so the rule pointed at nothing — and a missing file reads as "no
    # history" rather than "not wired up yet".
    history_path = repo_root / ".agent-history.log"
    if not history_path.exists():
        history_path.write_text(
            "# .agent-history.log — append-only record of agent sessions.\n"
            "# Read at session start (pillar 5): unresolved MAJOR/CRITICAL entries\n"
            "# are things a previous session could not finish, and repeating them\n"
            "# is the failure this log exists to prevent.\n"
            "# Written by scripts/agent_logger.py; safe to read, do not rewrite.\n"
        )
        print("✅ Seeded .agent-history.log")

    for skill in rules.get("skills", []):
        skill_dir = repo_root / ".agents" / "skills" / skill["id"]
        skill_path = skill_dir / "skill.md"
        if not skill_path.exists():
            skill_dir.mkdir(parents=True, exist_ok=True)
            skill_path.write_text(_render_skill(skill, rules, ctx))

    if rules.get("skills"):
        print(
            f"✅ Written Antigravity skill files ({', '.join(s['id'] for s in rules['skills'])}) from agent-rules.yaml"
        )


def _check_drift(repo_root: Path, rules: dict, stack: str, ctx: dict[str, str]) -> bool:
    """Print a diff for any committed IDE config file that no longer matches
    what agent-rules.yaml would generate. Returns True if clean (no drift)."""
    clean = True

    checks = [
        (repo_root / ".cursorrules", _render_cursorrules(rules, stack, ctx)),
        (repo_root / "CLAUDE.md", _render_claude_md(rules, ctx)),
        (repo_root / "AGENTS.md", _render_agents_md(rules, stack, ctx)),
        (repo_root / "GEMINI.md", _render_gemini_md(rules, stack, ctx)),
        (
            repo_root / ".github" / "copilot-instructions.md",
            _render_copilot_instructions(rules, stack, ctx),
        ),
    ]
    for skill in rules.get("skills", []):
        skill_path = repo_root / ".agents" / "skills" / skill["id"] / "skill.md"
        checks.append((skill_path, _render_skill(skill, rules, ctx)))

    for path, expected in checks:
        if not path.exists():
            print(
                f"ℹ️  {path.relative_to(repo_root)} not generated yet — skipping drift check."
            )
            continue
        actual = path.read_text()
        if actual == expected:
            print(f"✅ {path.relative_to(repo_root)} matches agent-rules.yaml")
            continue
        clean = False
        print(f"❌ {path.relative_to(repo_root)} has drifted from agent-rules.yaml:")
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"committed/{path.name}",
            tofile=f"generated/{path.name}",
        )
        sys.stdout.writelines(diff)

    return clean


if __name__ == "__main__":
    main()
