"""
scripts/rules_port.py — AgentSmith as a rules provider (contract/rules/v1/protocol.md).

    rules_port.py render            the rule files this repository's agents read, as JSON
    rules_port.py check             whether the repository still holds them, as a decision
    rules_port.py render --write    place them here (this provider's convenience, not a contract verb)

The repository is the working directory, or the request's `cwd`; one JSON request
on stdin, one JSON answer on stdout; exit 3 when this provider cannot run here.

`place` and `state` are the contract's placement rules, and the CALLER's as much as
this provider's: `agentsmith sync` and `tenant adopt` place what any declared
rules provider renders with them (.agent-rfc/designs/rules-contract.md).
"""

from __future__ import annotations

import difflib
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

import gate_models as gm

EXIT_CANNOT_RUN = 3
FRAMEWORK_ROOT = Path(__file__).resolve().parents[1]
CATALOGUE = FRAMEWORK_ROOT / "templates" / "agent-rules.yaml"

# The markers the contract names. The begin line's text after the marker is
# free; only the region between the two lines is the provider's.
RULES_BEGIN = ("<!-- agentsmith:rules:begin — generated by `agentsmith tenant adopt` from AgentSmith's rules; "
               "edits inside this block are lost on the next run -->")
RULES_END = "<!-- agentsmith:rules:end -->"
_BLOCK = re.compile(r"^<!-- agentsmith:rules:begin[^\n]*\n(.*?)^<!-- agentsmith:rules:end -->[ \t]*(?:\n|\Z)",
                    re.S | re.M)


# ── Placement (the contract's) ────────────────────────────────────────────────


def block(text: str) -> str:
    return f"{RULES_BEGIN}\n{text.rstrip()}\n{RULES_END}\n"


def region(existing: str) -> Optional[str]:
    """The provider's region of a file, or None when it has no markers."""
    found = _BLOCK.search(existing)
    return None if found is None else found.group(1).rstrip("\n")


def place(existing: Optional[str], file: gm.RulesFile) -> str:
    """What the file holds once `file` is placed in it: a `whole` file is
    replaced; a `block` replaces the marked region, or is appended to a file
    that has none — the rest of the file is the tenant's and is kept."""
    if file.placement == "whole" or existing is None:
        return file.text if file.placement == "whole" else block(file.text)
    if _BLOCK.search(existing):
        return _BLOCK.sub(lambda _: block(file.text), existing, count=1)
    return existing.rstrip("\n") + "\n\n" + block(file.text)


def state(existing: Optional[str], file: gm.RulesFile) -> str:
    """`absent`, `current` or `drifted`. Text outside a block is never compared."""
    if existing is None:
        return "absent"
    if file.placement == "whole":
        return "current" if existing == file.text else "drifted"
    held = region(existing)
    return "current" if held is not None and held == file.text.rstrip() else "drifted"


# ── This provider's render ────────────────────────────────────────────────────


def _generator():
    """scripts/generate-ide-config.py — one renderer, loaded the one way scripts load each other."""
    from _shared import load_script

    return load_script("generate-ide-config")


def seed_history(root: Path) -> bool:
    """Seed the repository's .agent-history.log when it has none (tenant data,
    not a rule file — so not part of a render)."""
    return _generator().seed_history(root)


def generated_whole(text: str) -> bool:
    """A rule file this provider generated whole: its own opening lines — before
    any rules block — say so."""
    head = text.split("<!-- agentsmith:rules:begin", 1)[0].splitlines()[:10]
    return any("Auto-generated" in line and "agent-rules.yaml" in line for line in head)


def _ours(rel: str, existing: str, titles: dict[str, str]) -> bool:
    """Is this existing file one this provider wrote whole? An instruction file
    carries the generated header; a skill file opens with its skill's title."""
    if rel in titles:
        return existing.split("\n", 1)[0] == f"# {titles[rel]}"
    return generated_whole(existing)


def _read(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def render(root: Path) -> gm.RulesRender:
    """The rule files for `root`, from its committed declarations and this
    provider's catalogue — nothing from the environment or the git remote."""
    generator = _generator()
    rules = generator._load_rules(CATALOGUE)
    titles = {f".agents/skills/{skill['id']}/skill.md": skill["title"] for skill in rules.get("skills", [])}
    files = []
    for rel, text, kind in generator.render_files(root, rules, generator.declared_context(root)):
        existing = _read(root / rel)
        placement = "whole" if existing is None or _ours(rel, existing, titles) else "block"
        files.append(gm.RulesFile(path=rel, text=text, placement=placement, kind=kind))
    return gm.RulesRender(files=files)


def check(root: Path, rendered: Optional[gm.RulesRender] = None) -> gm.RulesCheck:
    """Does `root` still hold what `rendered` (default: this provider's render)
    would place? Absent files are reported, not drift: a repository may choose
    not to commit its rule files."""
    rendered = rendered if rendered is not None else render(root)
    states, report = [], []
    for file in rendered.files:
        existing = _read(root / file.path)
        found = state(existing, file)
        states.append(gm.RulesFileState(path=file.path, state=found))
        if found == "drifted":
            held = (existing if file.placement == "whole" else region(existing) or "").splitlines(keepends=True)
            want = (file.text if file.placement == "whole" else file.text.rstrip()).splitlines(keepends=True)
            report += difflib.unified_diff(held, want, fromfile=f"committed/{file.path}",
                                           tofile=f"rendered/{file.path}")
            report.append("\n")
    drifted = [s.path for s in states if s.state == "drifted"]
    counts = {name: sum(1 for s in states if s.state == name) for name in gm.RULES_STATES}
    summary = ", ".join(f"{n} {name}" for name, n in counts.items() if n)
    if drifted:
        text = (f"{len(drifted)} rule file(s) no longer say what the rules provider renders: "
                f"{', '.join(drifted)}. `agentsmith sync` (or `agentsmith rules render --write`) brings them "
                "back; a repository's own text goes outside the marked block, and its notes in "
                "process-gates.json `extends`.")
        return gm.RulesCheck(decision="deny", text=text, report="".join(report) + f"Rule files: {summary}.",
                             files=states)
    return gm.RulesCheck(decision="allow", text=f"Rule files: {summary or 'none rendered'}.",
                         report=f"Rule files: {summary or 'none rendered'}.", files=states)


def write(root: Path, rendered: gm.RulesRender) -> list[str]:
    """Place every file of a validated render. Returns the paths whose bytes
    changed."""
    changed = []
    for file in rendered.files:
        target = root / file.path
        existing = _read(target)
        placed = place(existing, file)
        if placed != existing:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(placed, encoding="utf-8")
            changed.append(file.path)
    return changed


# ── The command ──────────────────────────────────────────────────────────────


def _repository(request: gm.RulesRequest) -> Path:
    if request.cwd:
        return Path(request.cwd)
    top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=False)
    return Path(top.stdout.strip()) if top.returncode == 0 and top.stdout.strip() else Path.cwd()


def _traced(verb: str, root: Path, run):
    """One `gate.rules_<verb>` span, fail-open like every gate span."""
    try:
        import gate_tracing as gt
    except Exception:  # fail-open: tracing never changes an answer
        return run(None)
    with gt.gate_span(f"rules_{verb}", root=root, ide="neutral") as span:
        result = run(span)
    gt.flush()
    return result


def main(argv: Optional[list[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    verb = args[0] if args else ""
    if verb not in ("render", "check") or any(a not in ("--write",) for a in args[1:]) \
            or ("--write" in args and verb != "render"):
        print("usage: rules_port.py render [--write] | check   (contract/rules/v1/protocol.md)", file=sys.stderr)
        return 2
    if not CATALOGUE.is_file():
        print(f"rules provider cannot run here: no catalogue at {CATALOGUE}", file=sys.stderr)
        return EXIT_CANNOT_RUN
    try:
        import yaml  # noqa: F401 — the catalogue is YAML
    except ImportError:
        print(f"rules provider cannot run here: {sys.executable} lacks pyyaml — run install-ai-stack.sh",
              file=sys.stderr)
        return EXIT_CANNOT_RUN
    raw = "" if sys.stdin.isatty() else sys.stdin.read()
    try:
        request = gm.RulesRequest.model_validate_json(raw or "{}")
    except gm.ValidationError as exc:
        print(f"rules provider: the request is not a JSON object ({exc.errors()[0]['msg']})", file=sys.stderr)
        return 2
    root = _repository(request)

    def run(span) -> int:
        rendered = render(root)
        if verb == "render" and "--write" in args:
            for path in write(root, rendered):
                print(f"✅ Written {path}")
            outcome = {"decision": "written", "files": len(rendered.files)}
        elif verb == "render":
            print(rendered.model_dump_json())
            outcome = {"decision": "rendered", "files": len(rendered.files)}
        else:
            answer = check(root, rendered)
            print(answer.model_dump_json())
            outcome = {"decision": answer.decision, "files": len(answer.files)}
        if span is not None:
            span.set_attribute("agent.decision", outcome["decision"])
            span.set_attribute("agent.rules.files", outcome["files"])
        return 0

    return _traced(verb, root, run)


if __name__ == "__main__":
    sys.exit(main())
